name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Archive
        run: |
          zip -r vitalsource-downloader.zip . -x "venv/*" "output/*" ".git/*" ".github/*"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: vitalsource-downloader.zip
          generate_release_notes: true
